import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import NavBar from "@/components/navigation/NavBar";
import AuthProvider from "@/components/AuthProvider";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import CartProvider from "@/context/CartProvider";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}
      > <CartProvider>
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem disableTransitionOnChange>
        <AuthProvider>
        <NavBar />
        {children}
        <Toaster />
        
        </AuthProvider>
        </ThemeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
